- hosts: nagios
  gather_facts: false

  roles:
    - {role: server-nagios, become: true}


- hosts: snmphost
  become: true
  gather_facts: false

  tasks:
    - name: install snmp deamon
      apt: name={{item}} state=present
      with_items:
        - snmpd
      notify: restart snmpd

    - name: create snmpd config file
      template:
        src: etc_snmp_snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
        mode: 0600
      notify: restart snmpd

  handlers:
    - name: restart snmpd
      service: name=snmpd state=restarted

- hosts: webserver
  become: true
  gather_facts: false

  tasks:
    - name: install lighttpd
      apt: name={{ item}} state=present
      with_items:
        - lighttpd
      notify: restart lighttpd

  handlers:
    - name: restart lighttpd
      service: name=lighttpd state=restarted
