- hosts: nagios

  roles:
    - {role: server-nagios, become: true}


- hosts: snmphost
  become: true

  tasks:
    - name: install snmp deamon
      apt: name={{item}} state=present
      with_items:
        - snmpd
      notify: restart snmpd

  handlers:
    - name: restart snmpd
      service: name=snmp state=restarted

- hosts: webserver
  become: true

  tasks:
    - name: install lighttpd
      apt: name={{ item}} state=present
      with_items:
        - lighttpd
      notify: restart lighttpd

  handlers:
    - name: restart lighttpd
      service: name=lighttpd state=restarted
